### ISSUE TITLE
not switching tool under certain conditions

### ISSUE THREAD

**Issue by pesegolsson** [ps-dps/Multitool#1]
noticed that the multitool 4.0 struggle to switch tools if there are non full blocks in adjacent blocks. shulk vein, trapdoors, glow lichen etc

can be frustrating when you for example build a stone/basalt generators and use trapdoors or glow lichen to hold back the water as you get stuck with an axe/hoe instead of it switching to a pickaxe.

is there anything you can do about this or is it just some quirk of how java works and we have to live with and craft special tools for those farms etc.

**Comment by PuckiSilver** [comment]
Hey,

it is theoretically possible to do so but makes the pack way more complex and might impact performance by a lot.
As I want to keep the pack as light and compatible as possible, I won't change that.

On a technical level:
I check a specific block (a 1x1x1 cube) for a certain block and not the block's hitbox. There sadly is no native way to check the hitbox so doing these checks requires many small checks and would therefore be expensive.

So currently we'll have to live with it
~PuckiSilver
