### ISSUE TITLE
{Suggestion} Ability to add custom tools

### ISSUE THREAD

**Issue by Poke5555** [ps-dps/Multitool#2]
I was wondering if you could add a config that would allow pack creators to add multitools for modded tools. This is currently the best tool combination mod ive found :)
I'm currently on version multitool-v4.0.1 for 1.19.2

**Comment by PuckiSilver** [comment]
Doing it using a config might be tough, since this is a data pack at it's core, but I could add a script that generates the multi tool pack/mod for specified tools

It's a thing I'll keep on my mind for now

**Comment by Poke5555** [comment]
Awesome. thanks for the reply

**Comment by PuckiSilver** [comment]
Hey, you can now generate the Multitool pack for any family of tools, I added a part in the README that should explain how to do that

This will currently only generate a data pack, so the zip file you put into your `<woldname>/datapacks/` folder, a version for mod loaders might follow at some point

If you have any trouble with it, please let me know

**Comment by Poke5555** [comment]
Thank you for making a system for this. I keep getting this error whenever i run beet, im not sure if its a problem with my install of beet or something. thank you for the help :)
![image](https://user-images.githubusercontent.com/21167484/233798031-c3c8776d-5f02-49fd-b809-6ceb973c582d.png)

**Comment by PuckiSilver** [comment]
How does your folder look? It looks like it can't find the plugin `/plugins/generate_multitool`
For faster communication you can also add me on Discord if you prefer `PuckiSilver#2557`
