### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ollo-t** [ps-dps/Multitool#3]
i was trying to get a multitool on oneblock and I got unlimited pickaxes and I don't want it pls

**Comment by PuckiSilver** [comment]
Remove the "Unlock Recipes" data pack by vanilla tweaks and replace it with a pack like [this one](https://www.planetminecraft.com/data-pack/wasd-unlock-all-recipes/).

Because of the way the crafting recipes are implemented, you can't use a simple "unlock all recipes" data pack.
