### ISSUE TITLE
So about mod loaders tag ?

### ISSUE THREAD

**Issue by DrShadox** [ps-dps/Multitool#7]
Files of the mod claim be for "Fabric Forge NeoForge Quilt" 
(all at once on all file (except datapack) so its very weird and its already an issue itself)

When trying to made it load on a forge instalation the game say me it's a fabric mod.

So if the mod is for Fabric why put Forge/NeoForge/Quilt as tag on mod file ?

Exemple :
![image](https://github.com/ps-dps/Multitool/assets/21160703/b693eb25-ed34-4cde-b19a-525192ee78ef)

**Comment by PuckiSilver** [comment]
The tool I use to package the files worked for all 4 loaders in the past and nothing about it changed — I have not checked it for the mods in the latest version and assumed they'd work

I will change it for the released versions. Thanks for bringing it to my notice and sorry for misleading you.

If I get around to it, I will fix the mods to work with forge/neoforge.

**Comment by DrShadox** [comment]
Thanks your for your answer, i hope you succed (for that and others things ^^).
Have a nice day.
